apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server
  namespace: zoochacha
spec:
  replicas: 1  # 서버는 확장 가능하도록 설정
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
    spec:
      serviceAccountName: admin-service-sa
      containers:
        - name: admin-server
          image: 651706756261.dkr.ecr.ap-northeast-2.amazonaws.com/admin-service:86
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          command: ["gunicorn"]
          args: ["--bind", "0.0.0.0:8001", "--workers", "4", "--timeout", "300", "--log-level", "debug", "app:app"]
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: admin-service-secret
                  key: FLASK_SESSION_SECRET_KEY
            - name: KAKAO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: admin-service-secret
                  key: KAKAO_API_KEY
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: admin-service-secret
                  key: COGNITO_CLIENT_SECRET
            - name: AUTHORIZE_REDIRECT_URL
              valueFrom:
                secretKeyRef:
                  name: admin-service-secret
                  key: AUTHORIZE_REDIRECT_URL
            - name: AWS_REGION
              value: "ap-northeast-2"
            - name: SQLALCHEMY_DATABASE_URI
              value: "mysql+pymysql://admin:zoochacha2024@zoochacha-db.cxqxvqvxvpxm.ap-northeast-2.rds.amazonaws.com:3306/zoochacha"
            - name: ADMIN_SERVICE_URL
              value: "/admin"
            - name: MAP_SERVICE_URL
              value: "/map"
            - name: RESERVATION_SERVICE_URL
              value: "/reservation"
            - name: PARKINGLOT_SERVICE_URL
              value: "/parkinglot"
            - name: RESERVATION_DETAIL_SERVICE_URL
              value: "/reservation-detail"
            - name: FLASK_DEBUG
              value: "1"
            - name: PYTHONUNBUFFERED
              value: "1"
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: admin-server
  namespace: zoochacha
spec:
  selector:
    app: admin-server
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-service-sa
  namespace: zoochacha
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::651706756261:role/zoochacha-admin-secrets-manager
